version: '3.8'

services:
  postgres_source:
    image: postgres:14
    environment:
      POSTGRES_USER: dwh_user
      POSTGRES_PASSWORD: dwh_password
      POSTGRES_DB: source_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init_source_db.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_source_data:/var/lib/postgresql/data

  postgres_replica:
    image: postgres:14
    environment:
      POSTGRES_USER: dwh_user
      POSTGRES_PASSWORD: dwh_password
      POSTGRES_DB: replica_db
    ports:
      - "5433:5432"
    volumes:
      - ./sql/init_replica_db.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_replica_data:/var/lib/postgresql/data

  postgres_ods:
    image: postgres:14
    environment:
      POSTGRES_USER: dwh_user
      POSTGRES_PASSWORD: dwh_password
      POSTGRES_DB: ods_db
    ports:
      - "5434:5432"
    volumes:
      - ./sql/init_ods_db.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_ods_data:/var/lib/postgresql/data

  clickhouse_dds:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./sql/init_dds_db.sql:/docker-entrypoint-initdb.d/init.sql
      - clickhouse_dds_data:/var/lib/clickhouse

  clickhouse_marts:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - ./sql/init_marts_db.sql:/docker-entrypoint-initdb.d/init.sql
      - clickhouse_marts_data:/var/lib/clickhouse

  airflow:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres_source
      - postgres_replica
      - postgres_ods
      - clickhouse_dds
      - clickhouse_marts
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://dwh_user:dwh_password@postgres_source/source_db
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: webserver

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana

volumes:
  postgres_source_data:
  postgres_replica_data:
  postgres_ods_data:
  clickhouse_dds_data:
  clickhouse_marts_data:
  grafana_data:
