version: '3.8'

services:
  postgres_source:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-dwh_user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-dwh_password}
      POSTGRES_DB: ${DATABASE_NAME:-source_db}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - ./sql/init_source_db.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_source_data:/var/lib/postgresql/data
    networks:
      - dwh_network
      - system_design_network

  postgres_replica:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-dwh_user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-dwh_password}
      POSTGRES_DB: replica_db
    ports:
      - "5433:5432"
    volumes:
      - ./sql/init_replica_db.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_replica_data:/var/lib/postgresql/data
    networks:
      - dwh_network

  postgres_ods:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-dwh_user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-dwh_password}
      POSTGRES_DB: ods_db
    ports:
      - "5434:5432"
    volumes:
      - ./sql/init_ods_db.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_ods_data:/var/lib/postgresql/data
    networks:
      - dwh_network

  clickhouse_dds:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./sql/init_dds_db.sql:/docker-entrypoint-initdb.d/init.sql
      - clickhouse_dds_data:/var/lib/clickhouse
    networks:
      - dwh_network

  clickhouse_marts:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - ./sql/init_marts_db.sql:/docker-entrypoint-initdb.d/init.sql
      - clickhouse_marts_data:/var/lib/clickhouse
    networks:
      - dwh_network

  airflow:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres_source
      - postgres_replica
      - postgres_ods
      - clickhouse_dds
      - clickhouse_marts
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DATABASE_USERNAME:-dwh_user}:${DATABASE_PASSWORD:-dwh_password}@postgres_source/${DATABASE_NAME:-source_db}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      KAFKA_BROKER: ${KAAS_BROKER_HOST:-kafka}:${KAAS_BROKER_PORT:-9092}
      TOPIC_NAME_RESULTS: ${TOPIC_NAME_RESULTS:-results}
      TOPIC_NAME_TRIGGERS: ${TOPIC_NAME_TRIGGERS:-triggers}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: webserver
    networks:
      - dwh_network
      - system_design_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource
    networks:
      - dwh_network
      - system_design_network

networks:
  dwh_network:
    driver: bridge
  system_design_network:
    external: true
    name: hse-system-design_default

volumes:
  postgres_source_data:
  postgres_replica_data:
  postgres_ods_data:
  clickhouse_dds_data:
  clickhouse_marts_data:
  grafana_data:
